### ISSUE TITLE
cannot find symbol variable CollapsingAppBarLayout_LayoutParams

### ISSUE THREAD

**Issue by hvar90** [ahmadmuzakki29/subtitle-collapsingtoolbar#2]
> myproyect/subtitlecollapsingtoolbar/src/main/java/com/muzakki/ahmad/widget/CollapsingToolbarLayout.java
>  Error:(1069, 32) error: cannot find symbol variable CollapsingAppBarLayout_LayoutParams
>  Error:(1071, 32) error: cannot find symbol variable CollapsingAppBarLayout_LayoutParams_layout_collapseMode
>  Error:(1074, 32) error: cannot find symbol variable CollapsingAppBarLayout_LayoutParams_layout_collapseParallaxMultiplier

>  Error:Execution failed for task ':subtitlecollapsingtoolbar:compileReleaseJavaWithJavac'.
>  Compilation failed; see the compiler error output for details.

the problem is with this method 

```
 public LayoutParams(Context c, AttributeSet attrs) {
            super(c, attrs);

            TypedArray a = c.obtainStyledAttributes(attrs,
                    R.styleable.CollapsingAppBarLayout_LayoutParams);
            mCollapseMode = a.getInt(
                    R.styleable.CollapsingAppBarLayout_LayoutParams_layout_collapseMode,
                    COLLAPSE_MODE_OFF);
            setParallaxMultiplier(a.getFloat(
                    R.styleable.CollapsingAppBarLayout_LayoutParams_layout_collapseParallaxMultiplier,
                    DEFAULT_PARALLAX_MULTIPLIER));
            a.recycle();
        }
```

**Comment by jekiapp** [comment]
I'm working on supporting newest SDK
