### ISSUE TITLE
there is not a expandedSubtitleTextAppearance

### ISSUE THREAD

**Issue by hvar90** [ahmadmuzakki29/subtitle-collapsingtoolbar#5]
is necessary to have a  expandedSubtitleTextAppearance like expandedTitleTextAppearance because also the subtitle needs a shadow because if the word is white and the background is white so the word wont be visible

**Comment by jekiapp** [comment]
this issue should not very hard to solve but still it takes time. I'm gonna look forward to it on my spare time, or maybe yo could submit PR to fix this

**Comment by hvar90** [comment]
i have fixed the problem, but I don't know if my solution is good for everybody, because I thought that is redundant put again the same code to put the same shadow of the title to the subtitle, so my solution was to share the same shadow for both

so, i have add mSubPaint.setShadowLayer next to mTextPaint.setShadowLayer  in CollapsingTextHelper

```
mTextPaint.setShadowLayer(
                lerp(mExpandedShadowRadius, mCollapsedShadowRadius, fraction, null),
                lerp(mExpandedShadowDx, mCollapsedShadowDx, fraction, null),
                lerp(mExpandedShadowDy, mCollapsedShadowDy, fraction, null),
                blendColors(mExpandedShadowColor, mCollapsedShadowColor, fraction));

//new code 
mSubPaint.setShadowLayer(
                lerp(mExpandedShadowRadius, mCollapsedShadowRadius, fraction, null),
                lerp(mExpandedShadowDx, mCollapsedShadowDx, fraction, null),
                lerp(mExpandedShadowDy, mCollapsedShadowDy, fraction, null),
                blendColors(mExpandedShadowColor, mCollapsedShadowColor, fraction));
        
```
